# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

#[plugins.zsh-autocomplete]
#github = 'marlonrichert/zsh-autocomplete'
#use = ["zsh-autocomplete.plugin.zsh"]

[plugins.p10k]
github = 'romkatv/powerlevel10k'
use = ["powerlevel10k.zsh-theme"]

[plugins.ohmyzsh]
github = 'ohmyzsh/ohmyzsh'
use = ["plugins/dotenv/dotenv.plugin.zsh", "plugins/direnv/direnv.plugin.zsh"]

[plugins.conda-zsh-completion]
github = 'esc/conda-zsh-completion'
apply = []

[plugins.zsh-completion]
github = 'zsh-users/zsh-completions'
apply = []

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
use = ["zsh-syntax-highlighting.zsh"]

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ["zsh-autosuggestions.zsh"]

[plugins.asdf]
github = 'asdf-vm/asdf'
use = ["lib/asdf.sh"]
